import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

import { Manrope } from "next/font/google";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="PT-BR"
      className={`${manrope.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <Navbar></Navbar>
        </header>

        <main className="flex-1">
          {children}
        </main>

        <footer>
          <Footer></Footer>
        </footer>

      </body>
    </html>
  );
}
